# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "group", # <group_parameters>
  "parameter", # <group_parameters>
  "model", # <expert_parameters>
  "parameter", # <expert_parameters>
  "expert.value", # <expert_parameters>
  "time", # <mod_exposurefile_input_server>
  "conc", # <mod_exposurefile_input_server>
  "time", # <mod_exposuretable_input_server>
  "conc", # <mod_exposuretable_input_server>
  "time", # <mod_exposuretoxswa_input_server>
  "conc", # <mod_exposuretoxswa_input_server>
  "time", # <mod_forcings_input_server>
  "value", # <mod_forcings_input_server>
  ".", # <mod_init_input_server>
  ".", # <mod_parameter_input_server>
  ".", # <mod_input_fields_server>
  "time", # <mod_prediction_server>
  "conc", # <mod_prediction_server>
  NULL
))
